### ISSUE TITLE
[Moveout] overwrite should be mandatory

### ISSUE THREAD

**Issue by danielo515** [Drugoy/Autohotkey-scripts-.ahk#11]
Hello,

Currently if overwrite is not set, any action will be performed on files matching a rule. With this behavior selecting something in overwrite drop-down should be mandatory. The other option is to have a fallback if this option is not set, for example move if there is no conflict.

**Comment by Drugoy** [comment]
Hi,

Probably, I should've commented on this long time ago.
MoveOut is not my script, I just found it useful once. But since then - I haven't used it and I don't intend to improve it.
If anyone suggests a patch - I'll accept it, but I honestly doubt anyone would, so I close this issue.
