### ISSUE TITLE
[moveout] FileMove does not understand yes or no as flags

### ISSUE THREAD

**Issue by danielo515** [Drugoy/Autohotkey-scripts-.ahk#12]
About line 133 you can see the following code

```
  If replace=No
    FileMove,%longpath%,%target%,%replace%
  Else
  If replace=Yes
    FileMove,%longpath%,%target%,%replace%
```

As long as I know, fileMove does not understand yes and no as parameter. 
And if you are going to pass the replace value as parameter, why not just check both and just call once?

```
  If replace=No or replace=yes
    FileMove,%longpath%,%target%,%replace%
```

Please note that I don't have a deep knowledge of AHK and I'm just assuming the most usual about programming in general.

**Comment by Drugoy** [comment]
Hi,

Probably, I should've commented on this long time ago.
MoveOut is not my script, I just found it useful once. But since then - I haven't used it and I don't intend to improve it.
If anyone suggests a patch - I'll accept it, but I honestly doubt anyone would, so I close this issue.
