### ISSUE TITLE
DetachVideo

### ISSUE THREAD

**Issue by becauseim** [Drugoy/Autohotkey-scripts-.ahk#14]
Так понимаю, публичная версия DetachVideo уже не работает. Существует ли обновленная версия данного сценария?

**Comment by Drugoy** [comment]
Не существует, но и актуальность оно свою потеряло (по крайней мере для меня) практически сразу: оказалось, что для firefox существует дополнение PopVideo, которое умеет то же самое.
Я больше держу этот скрипт ради демонстрации самой идеи, что на ahk можно делать забавные штуки.
Я даже как-то пытался подправить этот скрипт используя Acc.ahk (Acc Lib by Sean and jethrow), но у меня не получилось, с acc тяжело работать.
И может быть я ошибаюсь, но у меня сложилось впечатление, будто лиса так устроена, что у неё нет надёжной acc-структуры, по которой можно было бы получить путь к элементу с видео с текущей вкладки.

**Comment by Drugoy** [comment]
Issue закрываю, т.к. у меня нет желания исправлять этот скрипт, но патч я бы принял.

**Comment by becauseim** [comment]
На самом деле, было бы круто иметь подобный сценарий для выноса видео в отдельный интерфейс, который при желании, можно было бы разместить над окном рабочей программы, например, Можно ли такое реализовать посредством расширения для браузера?
