### ISSUE TITLE
[MasterScript.ahk] Start without showing window

### ISSUE THREAD

**Issue by acicovic** [Drugoy/Autohotkey-scripts-.ahk#17]
Hi Drugoy,

Thank you for your script collection. I want to start MasterScript on windows startup in hidden/tray mode (I don't want its window to pop-up).

I see no settings that would control this behavior. Is there a way to do this?

Thanks!

**Comment by Drugoy** [comment]
Hi acicovic,

Just remove/comment line #59.
I probably should've made it an option.

**Comment by acicovic** [comment]
Hi, Thanks!

If you make a future release, I think that making it an options makes sense.

Thanks again.
