### ISSUE TITLE
ACC viewer

### ISSUE THREAD

**Issue by marius-sucan** [Drugoy/Autohotkey-scripts-.ahk#18]
Hello!

I am interested in the ACC viewer script. Would you be interested in making improvements to it?

I am developing a script for people with poor eye-sight and I integrated ACC viewer into it, but I see no work has been put into it from 2012/2013... and it has a few bugs, but I am not good at DLL calls to make fix it myself...

Thank you very much.

Best regards, Marius.

**Comment by Drugoy** [comment]
Hello, Marius.

I'm sorry, but I am no longer using neither Windows nor AutoHotkey.

Also, I'm not the author of Acc.ahk and I also don't fully understand that script. It was long abandoned and had had some bugs way before I adopted it for my needs.

Good luck with Acc, Marius.
