### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by SpiritSeal** [Drugoy/Autohotkey-scripts-.ahk#24]
I tried to clone the dir and Windows defender picked up the scripts as trojans. Is this normal for zipped AHK scripts?

**Comment by Drugoy** [comment]
I don't know, I always disabled Windows Defender as the most useless antivirus-like program.

**Comment by Drugoy** [comment]
What happens if you unzip it? Which file then will Windows Defender claim as infected?

**Comment by SpiritSeal** [comment]
It didn't let me even keep the zipped file on my computer. :(

**Comment by SpiritSeal** [comment]
This is what it looks like, the file was just not even allowed to stay on my computer. 
![image](https://user-images.githubusercontent.com/45369057/72769824-4de40880-3bb9-11ea-9ced-bc445dca49e7.png)

**Comment by SpiritSeal** [comment]
found a way to bypass it, 
![image](https://user-images.githubusercontent.com/45369057/72769949-a9ae9180-3bb9-11ea-9af7-26ca0b5a83b9.png)
I would think that since Windows Defender strongly disagrees with unverified ahk scripts being run, it would also have a problem with them being downloaded into a zipped folder.

**Comment by Drugoy** [comment]
What does 'See details' button show?
Can you try to clone the repo via git (not zip) and see which file exactly your antivirus barks at?

**Comment by SpiritSeal** [comment]
[It just goes here](https://support.google.com/chrome/answer/2898334?visit_id=637152418591897377-655590147&hl=en&rd=2#virus).

It git clones just fine with no issues 
![2020-01-21](https://user-images.githubusercontent.com/45369057/72848828-acb18c80-3c62-11ea-9f0d-fed2dfcb6b4f.png)

**Comment by SpiritSeal** [comment]
Its prob just chrome doing that tbh

**Comment by Drugoy** [comment]
So now your windows defender doesn't see a problem with the very same scripts?

Don't you find it kind of proving the useless of that util?

p.s.: the issue seems to be resolved, I guess? If so - please, close the ticket then.

**Comment by SpiritSeal** [comment]
In Windows Defender's defense, it does seem like a good idea to block unsigned executables from downloading off of a browser like Chrome, since many people don't really know the risks that they are accepting when running some executables from unverified sources, whereas if you are pulling it using git, you likely know what you are doing, at least to some degree. I will agree that it is kind of unsafe as an antivirus **not** to check all incoming traffic regardless. 

p.s.- The scripts work as great as they sound, thank you for compiling this repo!
